# Profile to be added after the h2 one to override the values to enable Flyway migrations
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
