@startuml
[Mapper] <<io.skillia.mapper>>
[DTO] <<io.skillia.dto..>>
[Entity] <<io.skillia.persistence.entity>>
[Repository] <<io.skillia.persistence.repo>>

[Mapper] --> [DTO]
[Mapper] --> [Entity]
[Repository] -> [DTO]
[Repository] -> [Entity]
@endum